--- #YAML:1.0
name:                String-Random-NiceURL
version:             0.02
abstract:            random ID strings suitable for URLs.
license:             ~
author:              
    - Andrew Chilton <andy@chilts.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Exception:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
